version: 2
jobs:
  build:
    working_directory: ~/hql
    docker: 
      - image: circleci/clojure:lein-2.9.1
    environment:
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: hql-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: hql-{{ checksum "project.clj" }}
      - run: lein do test, uberjar
      - store_artifacts:
          path: target/uberjar/hql.jar
          destination: uberjar
      - run: lein with-profile test cloverage --codecov
      - run: bash <(curl -s https://codecov.io/bash)
